/**:
  ros__parameters:
    preprocess:
      lidar_type: 2               # 1 for Livox, 2 for Velodyne, 3 for Ouster
      scan_line: 16
      scan_rate: 10               # Velodyne rate
      timestamp_unit: 2           # PointCloud2 timestamp unit
      blind: 2.0
      blind_for_human_pilot: 1.0

    mapping:
      acc_cov: 0.1
      gyr_cov: 0.1
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      fov_degree: 360.0
      det_range: 100.0
      extrinsic_est_en: false      # true: enable the online estimation of IMU-LiDAR extrinsic

      extrinsic_T: [ 0.0, 0.0, 0.0 ]
      extrinsic_R: [ 1.0, 0.0, 0.0,
                     0.0, 1.0, 0.0,
                     0.0, 0.0, 1.0 ]

    filter_size_map: 0.3

    publish:
      path_en: true
      scan_publish_en: true        # false: close all the point cloud output
      dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan
      scan_lidarframe_pub_en: true # true: output the point cloud scans in the LiDAR frame
      scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body frame
      scan_baseframe_pub_en: false # true: output the point cloud scans in the base frame

    pcd_save:
      pcd_save_en: false
      interval: -1

    verbose: true
    runtime_pos_log_enable: false
    point_filter_num_for_preprocessing: 1
    point_filter_num: 4
    max_iteration: 4
    cube_side_length: 1000.0
